[profile.default]
src = 'src'
test = 'test'
ignored_paths = [
    "src/Testing - Phase",
    "test/Testing - Phase (Mocks)",
    "script/Testing - Phase",
]

out = 'out'
libs = ['lib']
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 100

[fmt]
number_underscore = "thousands"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
local = "http://localhost:8545"

[profile.etherscan_api]
sepolia = "${ETHERSCAN_KEY}"
